--- 
excluded_pkgfiles: []

project_pubdir: /usr/local/www/public/code/
project_pubhost: deveiate
project_homepage: http://deveiate.org/webkit-rspec-formatter.html
gem_pubhost: rubygems.org
project_requirements: 
  Rspec-Bundle: ">=0"
  Textmate: ">=0"
release_smtphost: mail.faeriemud.org
project_description: |-
  This is a formatter for RSpec that takes advantage of some of the advanced features of the webkit
  HTML engine, like the one TextMate uses for its output.
release_mailto: Ruby-Talk List <ruby-talk@ruby-lang.org>
project_dependencies: 
  rspec-core: ">=2.0.1"
project_summary: A webkit-aware pretty formatter for RSpec
version_file: rspec/core/formatters/webkit.rb
additional_pkgfiles: 
- data/**/*
required_ruby_version: ""
dev_dependencies: {}

authors: 
  Michael Granger: ged@FaerieMUD.org
post_install_message: |-
  
  You can use this formatter from TextMate (if you're using RSpec 2.0.0 
  or later) bysetting the TM_RSPEC_OPTS shell variable (in the 
  'Advanced' preference pane) to:
  
      --format RSpec::Core::Formatters::WebKit
  
  Have fun!
project_name: WebKit-RSpec-Formatter
