#!/usr/bin/env rake

require 'hoe'

Hoe.plugin :mercurial
Hoe.plugin :signing

Hoe.plugins.delete :rubyforge

hoespec = Hoe.spec 'webkit-rspec-formatter' do
	self.readme_file = 'README.rdoc'
	self.developer 'Michael Granger', 'ged@FaerieMUD.org'
	self.extra_deps << ['rspec-formatter-webkit', '~> 2.1']
	self.version = '2.0.2'

	self.spec_extras[:post_install_message] = self.paragraphs_of( 'README.md', 3..5 ).join( "\n\n" )

	self.hg_sign_tags = false if self.respond_to?( :hg_sign_tags )

end

